In [142]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder ,LabelEncoder
from sklearn.feature_selection import SelectKBest, chi2, f_classif
from sklearn.impute import SimpleImputer

In [149]:
df=pd.read_excel('FS.xls')
df.shape

(45892, 18)

In [150]:
df.isnull().sum().sort_values(ascending=False)
df.dtypes
df=df.dropna(subset=['cumul_cmd']) 
df.shape
df.dtypes

first_name       object
last_name        object
potencial        object
activity         object
speciality       object
sector           object
locality         object
product          object
general_note     object
cumul_ech       float64
cumul_cmd       float64
cumul_sale      float64
cumul_pres      float64
cumul_visit       int64
moy_satisf        int64
visit_period      int64
frequency         int64
recency         float64
dtype: object

In [153]:
scale=LabelEncoder()
numerical_features=df.select_dtypes(exclude='object').columns
categorical_features=df.select_dtypes(include='object').columns
categorical_features

Index(['first_name', 'last_name', 'potencial', 'activity', 'speciality',
       'sector', 'locality', 'product', 'general_note'],
      dtype='object')

In [154]:
for i in numerical_features:
    df[i].fillna(df[i].median(),inplace=True)
for i in categorical_features:
    df[i].fillna('none',inplace=True) 
for i in categorical_features :
    df[i]=scale.fit_transform(df[i])

In [155]:
y= df['cumul_cmd']
X= df.drop('cumul_cmd', axis=1)
X.head(5)

first_name  last_name  potencial  activity  speciality  sector  locality  \
0        1203       2093          3         1          12      36       169   
1        1203       2093          3         1          12      36       169   
2        1203       2093          3         1          12      36       169   
3        1203       2093          3         1          12      36       169   
4        1203       2093          3         1          12      36       169   

   product  general_note  cumul_ech  cumul_sale  cumul_pres  cumul_visit  \
0       19           535        0.0         0.0         0.0            1   
1        0           535        0.0         0.0         0.0            1   
2       35           535        0.0         0.0         0.0            1   
3        1           535        0.0         0.0         0.0            1   
4       18           535        0.0         0.0         0.0            1   

   moy_satisf  visit_period  frequency  recency  
0           4             0          0     28.0  
1           4             0          0     28.0  
2           4             0          0     28.0  
3           4             0          0     28.0  
4           4             0          0     28.0

In [156]:
from sklearn.feature_selection import SelectKBest, chi2, f_classif
chi2(X,y)

(array([1.46259843e+05, 1.41507108e+05, 2.03916605e+03, 3.89408374e+00,
        2.69978682e+03, 5.72396100e+03, 6.27193055e+03, 6.61963342e+02,
        3.02706040e+03, 3.60424447e+02, 2.03620340e+04, 4.17081302e+01,
        5.77797865e+03, 1.52368836e-02, 8.31093604e+04, 8.25109587e+03,
        1.89540071e+03]),
 array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 8.37022794e-117,
        0.00000000e+000, 1.15892152e-055, 0.00000000e+000, 2.02082747e-001,
        0.00000000e+000, 1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]))

In [206]:
selector = SelectKBest(f_classif, k=15)

In [207]:
selector.fit(X, y)
selector.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True])

In [208]:
X.columns

Index(['first_name', 'last_name', 'potencial', 'activity', 'speciality',
       'sector', 'locality', 'product', 'general_note', 'cumul_ech',
       'cumul_sale', 'cumul_pres', 'cumul_visit', 'moy_satisf', 'visit_period',
       'frequency', 'recency'],
      dtype='object')